{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-stack-manager.mysql.serviceName" . }}
  labels:
    {{- include "k8s-stack-manager.mysql.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ required "mysql.auth.rootPassword must be set when mysql.enabled=true" .Values.mysql.auth.rootPassword | b64enc | quote }}
  {{- if .Values.mysql.auth.password }}
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
