{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-stack-manager.mysql.serviceName" . }}
  labels:
    {{- include "k8s-stack-manager.mysql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    {{- include "k8s-stack-manager.mysql.selectorLabels" . | nindent 4 }}
{{- end }}
