apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-stack-manager.fullname" . }}-backend
  labels:
    {{- include "k8s-stack-manager.backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.azurite.enabled }}
  AZURE_TABLE_ENDPOINT: "{{ include "k8s-stack-manager.azurite.serviceName" . }}:10002"
  {{- end }}
  {{- if .Values.otel.enabled }}
  OTEL_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ include "k8s-stack-manager.otel.serviceName" . }}:4317"
  OTEL_SERVICE_NAME: "k8s-stack-manager"
  OTEL_TRACE_SAMPLE_RATE: {{ .Values.otel.sampleRate | quote }}
  {{- end }}
