apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-stack-manager.backend.stableService" . }}
  labels:
    {{- include "k8s-stack-manager.backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
  selector:
    {{- include "k8s-stack-manager.backend.selectorLabels" . | nindent 4 }}
