{{- if .Values.backend.serviceAccount.create }}
{{- $annotations := deepCopy .Values.backend.serviceAccount.annotations }}
{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.secretStore.create (eq .Values.externalSecrets.azureKeyVault.authType "WorkloadIdentity") }}
{{- $_ := set $annotations "azure.workload.identity/client-id" (required "externalSecrets.azureKeyVault.workloadIdentity.clientId must be set when using WorkloadIdentity" .Values.externalSecrets.azureKeyVault.workloadIdentity.clientId) }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-stack-manager.fullname" . }}-backend
  labels:
    {{- include "k8s-stack-manager.backend.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
