{{- if .Values.argoRollouts.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-stack-manager.backend.canaryService" . }}
  labels:
    {{- include "k8s-stack-manager.backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "k8s-stack-manager.backend.selectorLabels" . | nindent 4 }}
{{- end }}
