{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-stack-manager.fullname" . }}-frontend-nginx
  labels:
    {{- include "k8s-stack-manager.frontend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
{{- end }}
