{{- if and .Values.frontend.enabled .Values.argoRollouts.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-stack-manager.frontend.canaryService" . }}
  labels:
    {{- include "k8s-stack-manager.frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
  selector:
    {{- include "k8s-stack-manager.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
